# Generated by Django 3.2.8 on 2022-04-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=10)),
                ('trainer', models.CharField(max_length=10)),
                ('trainee', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'institute',
            },
        ),
    ]
