# Generated by Django 3.2.8 on 2022-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_traineemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'module',
            },
        ),
    ]
