# Generated by Django 3.2.8 on 2022-05-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220428_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.CharField(max_length=100)),
                ('batchFor', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('licenseKey', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'manage-batch',
            },
        ),
        migrations.AlterField(
            model_name='trainermanagement',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
