# Generated by Django 3.2.8 on 2022-05-04 10:52

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220501_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('numOfQuestions', models.CharField(max_length=100)),
                ('mappingName', models.CharField(max_length=100)),
                ('status', models.CharField(default=None, max_length=150, verbose_name=course.models.StatusName)),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='StatusName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status_name',
            },
        ),
    ]
