# Generated by Django 3.2.8 on 2022-05-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_questionbank_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'semester_name',
            },
        ),
        migrations.RenameField(
            model_name='managebatch',
            old_name='EndDate',
            new_name='endDate',
        ),
        migrations.AlterField(
            model_name='managebatch',
            name='batchFor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
