# Generated by Django 3.2.8 on 2022-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20220517_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department_name',
            },
        ),
    ]
