# Generated by Django 3.2.8 on 2022-05-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_departmentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='managebatch',
            name='department',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='course.departmentname'),
        ),
    ]
