# Generated by Django 3.2.8 on 2022-05-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_managebatch_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentname',
            name='id',
        ),
        migrations.AlterField(
            model_name='departmentname',
            name='name',
            field=models.CharField(max_length=100, primary_key='True', serialize=False),
        ),
    ]
