# Generated by Django 3.2.8 on 2022-05-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20220519_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managebatch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.departmentname'),
        ),
    ]
