# Generated by Django 3.2.8 on 2022-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_managebatch_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
