# Generated by Django 3.2.8 on 2022-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_managebatch_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
