# Generated by Django 3.2.8 on 2022-05-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_departmentname_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managebatch',
            name='department',
            field=models.ForeignKey(blank=True, default='Free', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.departmentname'),
        ),
    ]
