# Generated by Django 3.2.8 on 2022-05-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20220519_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managebatch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.departmentname'),
            preserve_default=False,
        ),
    ]
