# Generated by Django 3.2.8 on 2022-05-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_alter_managebatch_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managebatch',
            name='department',
        ),
    ]
