# Generated by Django 3.2.8 on 2022-05-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_managebatch_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.statusname'),
        ),
    ]
