# Generated by Django 3.2.8 on 2022-05-23 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_alter_managebatch_departmentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managebatch',
            name='DepartmentName',
        ),
        migrations.AddField(
            model_name='managebatch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='course.departmentname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_id', to='course.statusname'),
        ),
    ]
