# Generated by Django 3.2.8 on 2022-05-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_traineemanagement_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageBatch',
        ),
    ]
