# Generated by Django 3.2.8 on 2022-05-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_delete_managebatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(max_length=100)),
                ('batchFor', models.CharField(blank=True, max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('licenseKey', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='course.departmentname')),
            ],
            options={
                'db_table': 'manage-batch',
            },
        ),
    ]
