# Generated by Django 3.2.8 on 2022-05-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_managebatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managebatch',
            name='department',
        ),
    ]
