# Generated by Django 3.2.8 on 2022-05-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_remove_managebatch_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='managebatch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='course.departmentname'),
            preserve_default=False,
        ),
    ]
